
package ee.ttu.ws.mattias_koosalu.employers;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "employersService", targetNamespace = "http://www.ttu.ee/vt_projekt/mattias_koosalu/134911IAPB", wsdlLocation = "file:/home/sammalsilm/kool/vt/projekt/company.wsdl")
public class EmployersService
    extends Service
{

    private final static URL EMPLOYERSSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYERSSERVICE_EXCEPTION;
    private final static QName EMPLOYERSSERVICE_QNAME = new QName("http://www.ttu.ee/vt_projekt/mattias_koosalu/134911IAPB", "employersService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/sammalsilm/kool/vt/projekt/company.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYERSSERVICE_WSDL_LOCATION = url;
        EMPLOYERSSERVICE_EXCEPTION = e;
    }

    public EmployersService() {
        super(__getWsdlLocation(), EMPLOYERSSERVICE_QNAME);
    }

    public EmployersService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYERSSERVICE_QNAME, features);
    }

    public EmployersService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYERSSERVICE_QNAME);
    }

    public EmployersService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYERSSERVICE_QNAME, features);
    }

    public EmployersService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployersService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployersPortType
     */
    @WebEndpoint(name = "employersPort")
    public EmployersPortType getEmployersPort() {
        return super.getPort(new QName("http://www.ttu.ee/vt_projekt/mattias_koosalu/134911IAPB", "employersPort"), EmployersPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployersPortType
     */
    @WebEndpoint(name = "employersPort")
    public EmployersPortType getEmployersPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ttu.ee/vt_projekt/mattias_koosalu/134911IAPB", "employersPort"), EmployersPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYERSSERVICE_EXCEPTION!= null) {
            throw EMPLOYERSSERVICE_EXCEPTION;
        }
        return EMPLOYERSSERVICE_WSDL_LOCATION;
    }

}
